from inspect import cleandoc

from koti import *
from koti.utils import *


class AnanicyModule(ConfigModule):

  def depends_on(self) -> list[ConfigItem]: return [
    Package("cachyos-mirrorlist")
  ]

  def provides(self) -> ConfigModuleGroups:
    return ConfigItemGroup(
      Package("ananicy-cpp"),

      SystemdUnit("ananicy-cpp.service"),

      PostHook(
        "restart ananicy service",
        execute = lambda: shell_interactive("systemctl restart ananicy-cpp.service")
      ),

      File(
        "/etc/ananicy.d/ananicy.conf",
        permissions = 0o444,
        content = cleandoc('''
        # managed by arch-config
        # Generated by ananicy-cpp at 2024-11-29 20:02:04.668520254
        check_freq = 20
        loglevel = info
        cgroup_realtime_workaround = true
        rule_load = true
        type_load = true
        log_applied_rule = false
        apply_latnice = false
        apply_oom_score_adj = true
        apply_ionice = true
        cgroup_load = true
        apply_sched = true
        apply_nice = true
      ''')),

      File("/etc/ananicy.d/arch-update.rules", permissions = 0o444, content = cleandoc('''
        # managed by arch-config
        {"name": "arch-update", "nice": 10}
      ''')),

      File("/etc/ananicy.d/audio-system.rules", permissions = 0o444, content = cleandoc('''
        # managed by arch-config
        {"name": "pipewire", "nice": -10, "latency_nice": -10}
        {"name": "wireplumber", "nice": -10, "latency_nice": -10}
        {"name": "pipewire-pulse", "nice": -10, "latency_nice": -10}
      ''')),

      File("/etc/ananicy.d/kwin.rules", permissions = 0o444, content = cleandoc('''
        # managed by arch-config
        {"name": "kwin_wayland", "nice": -10, "latency_nice": -10}
      ''')),

      File("/etc/ananicy.d/compilers.rules", permissions = 0o444, content = cleandoc('''
        # managed by arch-config
        {"name": "gcc",   "nice": 19, "latency_nice": 19, "sched": "batch", "ioclass": "idle"}
        {"name": "make",  "nice": 19, "latency_nice": 19, "sched": "batch", "ioclass": "idle"}
        {"name": "clang", "nice": 19, "latency_nice": 19, "sched": "batch", "ioclass": "idle"}
      ''')),

      File("/etc/ananicy.d/games.rules", permissions = 0o444, content = cleandoc('''
        # managed by arch-config
        {"name": "steam",   "nice": -5, "latency_nice": -5}
        {"name": "ryujinx", "nice": -5, "latency_nice": -5}
        {"name": "lutris",  "nice": -5, "latency_nice": -5}
        {"name": "heroic",  "nice": -5, "latency_nice": -5}
      ''')),

      File("/etc/ananicy.d/nextcloud.rules", permissions = 0o444, content = cleandoc('''
        # managed by arch-config
        {"name": "nextcloud", "nice": 10}
      ''')),
    )
