[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "koti"
version = "0.1.0"
description = "Declarative configuration manager"
license = "GPL-3.0-or-later"
authors = [{ name = "Manuel Bleichner" }]
requires-python = ">=3.12"


