services:
  pacoloco:
    restart: always
    container_name: pacoloco
    image: ghcr.io/anatol/pacoloco
    volumes:
    - /etc/pacman.d:/etc/pacman.d:ro
    - ./pacoloco.yaml:/etc/pacoloco.yaml:ro
    - ./cache:/var/cache/pacoloco:rw
    environment:
    - TZ=Europe/Berlin
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.pacoloco.loadbalancer.server.port=8000"
    - "traefik.http.routers.pacoloco.rule=Host(`pacoloco.fritz.box`)"
    - "traefik.http.routers.pacoloco.entrypoints=web"
    - "traefik.http.routers.pacoloco.middlewares=local-only"