#!/bin/bash

STATE=$(systemctl is-active cpufreq-adjuster.service)
if [[ "$STATE" == "active" ]]; then
  MODE=$(yq -r .mode /tmp/cpufreq.state.yaml)
  BASE=$(yq -r .base /tmp/cpufreq.state.yaml)
  if [[ "$MODE" == "auto" ]]; then
    MODE_DESC="base:${BASE}MHz"
  elif [[ "$MODE" == "fixed" ]]; then
    MODE_DESC="fixed:${BASE}MHz"
  elif [[ "$MODE" == "suspend" ]]; then
    MODE_DESC="suspended"
  else
    MODE_DESC="invalid mode"
  fi
else
  MODE_DESC="inactive"
fi

CURRENT=$(( $(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq) / 1000 ))
SMT="$(cat /sys/devices/system/cpu/smt/control)"
if [[ "$SMT" == "0" || "$SMT" == "off" ]]; then
  HYPERTHREADING="ht:off"
fi

GOVERNOR="$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor)"
if [[ "$GOVERNOR" == "performance" ]]; then
  GOVERNOR="perf"
elif [[ "$GOVERNOR" == "powersave" ]]; then
  GOVERNOR="eco"
fi

echo "CPU: ${CURRENT}MHz"
echo "${MODE_DESC} ${GOVERNOR} ${HYPERTHREADING}"