services:

  nextcloud-web:
    image: nextcloud # mit cron-Image synchron halten
    container_name: nextcloud-web
    restart: always
    depends_on:
    - nextcloud-postgres
    environment:
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "nextcloud"
      POSTGRES_HOST: "nextcloud-postgres"
      PHP_MEMORY_LIMIT: "8G"
      PHP_UPLOAD_LIMIT: "16G"
      APACHE_BODY_LIMIT: "0"
    volumes:
    - /var/opt/services/nextcloud/data:/var/www/html
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    - "traefik.http.routers.nextcloud-remote.rule=Host(`nextcloud.mbleichner.duckdns.org`)"
    - "traefik.http.routers.nextcloud-remote.entrypoints=websecure"
    - "traefik.http.routers.nextcloud-remote.tls.certresolver=letsencryptresolver"
    - "traefik.http.routers.nextcloud-local.rule=Host(`nextcloud.fritz.box`)"
    - "traefik.http.routers.nextcloud-local.entrypoints=web"
    - "traefik.http.routers.nextcloud-local.middlewares=local-only"

  nextcloud-cron:
    image: nextcloud
    container_name: nextcloud-cron
    entrypoint: /cron.sh
    restart: always
    depends_on:
    - nextcloud-postgres
    environment:
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "nextcloud"
      POSTGRES_HOST: "nextcloud-postgres"
    volumes:
    - /var/opt/services/nextcloud/data:/var/www/html

  nextcloud-postgres:
    image: postgres:16
    container_name: nextcloud-postgres
    restart: always
    environment:
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "nextcloud"
    volumes:
    - /var/opt/services/nextcloud/postgres:/var/lib/postgresql/data

  teamspeak:
    image: teamspeaksystems/teamspeak6-server
    container_name: teamspeak
    restart: always
    ports:
    - "0.0.0.0:9987:9987/udp"            # Audio/Video
    - "0.0.0.0:30033:30033"              # File Transfer
    - "127.0.0.1:10022:10022"            # ServerQuery (SSH)
    - "127.0.0.1:10080:10080"            # WebQuery
    environment:
      TSSERVER_LICENSE_ACCEPTED: "accept"
      TSSERVER_QUERY_SSH_ENABLED: "true"
      TSSERVER_QUERY_HTTP_ENABLED: "true"
    env_file:
    - /etc/opt/services/teamspeak.env  # should contain TSSERVER_QUERY_ADMIN_PASSWORD
    volumes:
    - /var/opt/services/teamspeak/data:/var/tsserver

  aurcache:
    # set up a custom repo name (once after initial start)
    # - cd /var/opt/services/aurcache/repo/x86_64
    # - sudo ln -s repo.db aurcache.db
    # - sudo ln -s repo.files aurcache.files
    image: ghcr.io/lukas-heiligenbrunner/aurcache
    container_name: aurcache
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/opt/services/aurcache/repo:/app/repo
    - /var/opt/services/aurcache/builds:/app/builds
    environment:
      TZ: "Europe/Berlin"
      DB_TYPE: "POSTGRESQL" # sqlite is pretty unstable and prone to random errors
      DB_USER: "aurcache"
      DB_PWD: "aurcache"
      DB_HOST: "aurcache-postgres"
      MAX_CONCURRENT_BUILDS: "3"
      BUILD_ARTIFACT_DIR: "/var/opt/services/aurcache/builds"  # refers to host path
      MIRRORLIST_PATH_X86_64: "/etc/pacman.d"                  # refers to host path
      MIRROR_RANK_SCHEDULE: null
      AUTO_UPDATE_SCHEDULE: "0 30 3,7,18 * * * *"              # same as pacoloco
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.aurcache-frontend.loadbalancer.server.port=8080"
    - "traefik.http.routers.aurcache-frontend.service=aurcache-frontend"
    - "traefik.http.routers.aurcache-frontend.rule=Host(`aurcache.fritz.box`)"
    - "traefik.http.routers.aurcache-frontend.entrypoints=web"
    - "traefik.http.routers.aurcache-frontend.middlewares=local-only"
    - "traefik.http.services.aurcache-repo.loadbalancer.server.port=8081"
    - "traefik.http.routers.aurcache-repo.service=aurcache-repo"
    - "traefik.http.routers.aurcache-repo.rule=Host(`aurcache.fritz.box`) && PathPrefix(`/x86_64/`)"
    - "traefik.http.routers.aurcache-repo.entrypoints=web"
    - "traefik.http.routers.aurcache-repo.middlewares=local-only"

  aurcache-postgres:
    image: postgres:18
    container_name: aurcache-postgres
    restart: always
    volumes:
    - /var/opt/services/aurcache/postgres:/var/lib/postgresql
    environment:
    - POSTGRES_PASSWORD=aurcache
    - POSTGRES_USER=aurcache

  satisfactory:
    build: { context: ./satisfactory }
    container_name: satisfactory
    restart: always
    ports:
    - "0.0.0.0:7777:7777/tcp"
    - "0.0.0.0:7777:7777/udp"
    - "0.0.0.0:8888:8888/tcp"
    - "0.0.0.0:8888:8888/udp"
    volumes:
    - "/var/opt/services/satisfactory/userhome:/home/ubuntu" # initial setup: sudo chown -R 1000:1000 /var/opt/services/satisfactory/userhome

  valheim:
    build: { context: ./valheim }
    container_name: valheim
    restart: always
    ports:
    - "0.0.0.0:2456:2456/udp"
    - "0.0.0.0:2457:2457/udp"
    - "0.0.0.0:2458:2458/udp"
    env_file:
    - /etc/opt/services/valheim.env  # should contain ServerPassword
    volumes:
    - "/var/opt/services/valheim/userhome:/home/ubuntu" # initial setup: sudo chown -R 1000:1000 /var/opt/services/valheim/userhome
