services:
  pihole:
    restart: always
    container_name: pihole
    image: pihole/pihole
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: "moepmoep"
    healthcheck:
      disable: true
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    volumes:
    - './etc-pihole:/etc/pihole'
    - './etc-dnsmasq.d:/etc/dnsmasq.d'
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.pihole.loadbalancer.server.port=80"
    - "traefik.http.routers.pihole.rule=Host(`pihole.fritz.box`)"
    - "traefik.http.routers.pihole.entrypoints=web"
    - "traefik.http.routers.pihole.middlewares=local-only,pihole-redirect"
    - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^http://pihole.fritz.box/?$"
    - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=http://pihole.fritz.box/admin/"